Feature('CreatePostForm');

Scenario('test something', (I) => {
    I.loginAsAdmin();
    I.amOnPage('/wp-admin');
    I.click('User Frontend');
    I.click('Post Forms');
    I.click('Add Form');
    I.moveCursorTo('.blank-form');
    I.click('Create Form');
        I.click('//*[@id="panel-form-field-buttons-post-fields"]/li[1]');
        I.click('//*[@id="panel-form-field-buttons-post-fields"]/li[2]');
        I.click('//*[@id="panel-form-field-buttons-post-fields"]/li[3]');
        I.click('//*[@id="panel-form-field-buttons-post-fields"]/li[4]');
        I.click('//*[@id="panel-form-field-buttons-taxonomies"]/li[1]');
        I.click('//*[@id="panel-form-field-buttons-taxonomies"]/li[2]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[1]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[2]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[3]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[4]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[5]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[6]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[7]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[8]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[9]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[10]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[11]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[12]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[13]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[14]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[15]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[16]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[17]');
        // pause();
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[18]');
        I.click('//*[@id="panel-form-field-buttons-custom-fields"]/li[19]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[1]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[2]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[3]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[4]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[5]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[6]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[7]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[8]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[9]');
        I.click('//*[@id="panel-form-field-buttons-others"]/li[10]');
        I.click('Settings', 'h2');
        I.checkOption('Enable Multistep');
        I.click('Save Form');
        I.click('Preview');
        // pause();
});
